"""
Builds the LangGraph `StateGraph` that orchestrates the whole system.

Flow:

    START -> memory -> router -> [rag | kg | tool | general] -> build_prompt -> generate -> memory_write -> END

The router decides, per query, exactly one of four paths:
    - rag      static knowledge base (vector search over scraped/ingested content)
    - kg       structured entity/relationship lookup (Neo4j)
    - tool     real-time computed/live info (datetime, calculator, web search)
    - general  open-domain question the knowledge base doesn't cover --
               answered directly from the LLM's (Groq) own knowledge

All four converge on build_prompt -> generate (Groq) -> memory_write
(PostgreSQL), so every answer is generated by a real LLM call, not just
extracted from retrieved text, and every turn is persisted for long-term,
cross-session memory.
"""

from __future__ import annotations

from functools import partial

from langgraph.graph import END, START, StateGraph

from memory_augmented_chatbot.memory_chatbot.src.knowledge_graph.graph_store import Neo4jGraphStore, get_graph_store
from memory_augmented_chatbot.memory_chatbot.src.llm.client import LLMClient, get_llm_client
from memory_augmented_chatbot.memory_chatbot.src.memory.memory_store import MemoryStore, get_memory_store
from memory_augmented_chatbot.memory_chatbot.src.orchestration import nodes
from memory_augmented_chatbot.memory_chatbot.src.orchestration.state import ChatState
from memory_augmented_chatbot.memory_chatbot.src.rag.retriever import Retriever


class ChatbotGraph:
    """
    Thin wrapper that owns the shared resources (retriever, graph store,
    memory store, LLM client) and compiles a LangGraph app bound to them.
    """

    def __init__(
        self,
        retriever: Retriever | None = None,
        graph_store: Neo4jGraphStore | None = None,
        memory_store: MemoryStore | None = None,
        llm_client: LLMClient | None = None,
    ):
        self.retriever = retriever or Retriever()
        self.graph_store = graph_store or get_graph_store()
        self.memory_store = memory_store or get_memory_store()
        self.llm_client = llm_client or get_llm_client()
        self.app = self._build()

    def _build(self):
        graph = StateGraph(ChatState)

        graph.add_node("memory", partial(nodes.memory_node, memory_store=self.memory_store))
        graph.add_node("router", partial(nodes.router_node, retriever=self.retriever))
        graph.add_node("rag", partial(nodes.rag_node, retriever=self.retriever))
        graph.add_node("kg", partial(nodes.kg_node, graph_store=self.graph_store))
        graph.add_node("tool", nodes.tool_node)
        graph.add_node("general", nodes.general_node)
        graph.add_node("build_prompt", nodes.build_prompt_node)
        graph.add_node("generate", partial(nodes.generation_node, llm_client=self.llm_client))
        graph.add_node("memory_write", partial(nodes.memory_write_node, memory_store=self.memory_store))

        graph.add_edge(START, "memory")
        graph.add_edge("memory", "router")

        graph.add_conditional_edges(
            "router",
            nodes.route_decision,
            {"rag": "rag", "kg": "kg", "tool": "tool", "general": "general"},
        )

        graph.add_edge("rag", "build_prompt")
        graph.add_edge("kg", "build_prompt")
        graph.add_edge("tool", "build_prompt")
        graph.add_edge("general", "build_prompt")

        graph.add_edge("build_prompt", "generate")
        graph.add_edge("generate", "memory_write")
        graph.add_edge("memory_write", END)

        return graph.compile()

    def chat(self, user_id: str, query: str) -> ChatState:
        initial_state: ChatState = {"user_id": user_id, "query": query}
        return self.app.invoke(initial_state)

    def save_artifacts(self):
        self.retriever.save()
