"""
Streamlit chat interface for the Memory-Augmented Chatbot.

Run with:
    streamlit run ui/app.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from memory_augmented_chatbot.memory_chatbot.src import config
from memory_augmented_chatbot.memory_chatbot.src.knowledge_graph.graph_store import get_graph_store
from memory_augmented_chatbot.memory_chatbot.src.memory.memory_store import get_memory_store
from memory_augmented_chatbot.memory_chatbot.src.orchestration.graph import ChatbotGraph
from memory_augmented_chatbot.memory_chatbot.src.rag.retriever import Retriever
from memory_augmented_chatbot.memory_chatbot.ui.style import ROUTE_LABELS, inject_custom_css

st.set_page_config(page_title="Memory-Augmented Chatbot", page_icon="🧠", layout="wide")
inject_custom_css()


@st.cache_resource
def load_chatbot() -> ChatbotGraph:
    try:
        retriever = Retriever.load()
    except FileNotFoundError:
        st.warning("No knowledge base found yet. Run `python -m scripts.build_knowledge_base` first.")
        retriever = Retriever()

    graph_store = get_graph_store()
    memory_store = get_memory_store()
    return ChatbotGraph(retriever=retriever, graph_store=graph_store, memory_store=memory_store)


chatbot = load_chatbot()

st.title("🧠 Memory-Augmented Chatbot")
st.caption("RAG + Neo4j Knowledge Graph + PostgreSQL Long-Term Memory, orchestrated with LangGraph, generated by Groq")

with st.sidebar:
    st.header("Session")
    user_id = st.text_input("User ID", value="demo_user")

    st.divider()
    st.subheader("🧠 Long-term memory")
    st.caption(f"PostgreSQL · {config.POSTGRES_HOST}:{config.POSTGRES_PORT}/{config.POSTGRES_DB}")
    facts = chatbot.memory_store.get_facts(user_id, limit=20)
    if facts:
        for f in facts:
            st.markdown(f"- {f.fact}")
    else:
        st.caption("No facts stored yet for this user.")

    if st.button("🗑️ Forget this user"):
        chatbot.memory_store.forget(user_id)
        st.success("Memory cleared.")
        st.rerun()

    st.divider()
    st.subheader("📊 Knowledge base stats")
    st.write(f"Chunks indexed (vector store): {len(chatbot.retriever.vector_store)}")
    gstats = chatbot.graph_store.stats()
    st.write(f"Neo4j entities: {gstats['num_entities']}")
    st.write(f"Neo4j relations: {gstats['num_relations']}")

if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

if prompt := st.chat_input("Ask me anything..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            result = chatbot.chat(user_id, prompt)
            answer = result.get("answer", "")
            route = result.get("route", "rag")
            st.markdown(f"`{ROUTE_LABELS.get(route, route)}`")
            st.markdown(answer)

            with st.expander("🔍 Debug: routing & retrieved context"):
                st.write(f"**Route:** {route}")
                if result.get("rag_context"):
                    st.markdown("**RAG context:**")
                    st.code(result["rag_context"])
                if result.get("kg_context"):
                    st.markdown("**Knowledge Graph context:**")
                    st.code(result["kg_context"])
                if result.get("tool_output"):
                    st.markdown("**Tool output:**")
                    st.code(result["tool_output"])
                if result.get("memory_facts"):
                    st.markdown("**Memory used:**")
                    st.code(result["memory_facts"])

    st.session_state.messages.append({"role": "assistant", "content": answer})
